//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТоварыНаСкладе
    {
        public string Код_товара { get; set; }
        public string Наименование { get; set; }
        public string Имя_поставщика { get; set; }
        public int Количество_вшт { get; set; }
        public string Статус { get; set; }
    
        public virtual Доставка Доставка { get; set; }
        public virtual Поставщик Поставщик { get; set; }
    }
}
